name: 'Saplings - Content type base'
description: 'Base configuration for Saplings content types.'
type: 'Site'
install:
  # Core.
  - content_moderation
  - link
  - media
  - node
  - responsive_image
  - taxonomy
  - text
  # Contrib.
  - focal_point
  - nomarkup
  - saplings_custom
config:
  import:
    # Core.
    content_moderation:
      - views.view.moderated_content
    # Contrib.
    focal_point: "*"
    saplings_custom: "*"
