name: 'Saplings - Content type base'
description: 'Shared configuration for Saplings content types.'
type: 'Site'
recipes:
  - saplings-content-base-header
  - saplings-content-base-seo
  - saplings-media
  - saplings-theme
install:
  # Core.
  - link
  - media
  - node
  - options
  - taxonomy
  - text
  # Contrib.
  - entity_reference_revisions
  - paragraphs
